### ISSUE TITLE
Any further development planned?

### ISSUE THREAD

**Issue by Rainer-Lang** [nshmura/RecyclerTabLayout#3]
I don't know if it's possible, but I have some ideas. ;-)
How about to add badges to tablayout or make the tablayout/viewpager not swipeable,...

**Comment by nshmura** [comment]
Thank you for your suggestions.

> add badges to tablayout

That is possible. Just use custom RecyclerView.Adapter.
Please see demo holder.
https://github.com/nshmura/RecyclerTabLayout/blob/master/demo/src/main/java/com/nshmura/recyclertablayout/demo/customview01/DemoCustomView01Adapter.java

> make the tablayout/viewpager not swipeable

Maybe possible.
Please see below answers.
http://stackoverflow.com/questions/25935890/best-way-to-disable-viewpager-paging
http://stackoverflow.com/questions/30222310/disable-scrolling-in-child-recyclerview-android

**Comment by shism2** [comment]
Any plans to use tablayout instead?

**Comment by nshmura** [comment]
RecyclerTabLayout is not replacement of TabLayout.
In normal use, TabLayout is good parts maintained by Google.
In case of using many tabs, RecyclerTabLayout will improve performance.
(Since TabLayout is implemented using LinearLayout, you would get poor performance from creating too many tabs.)
Please use the RecyclerTabLayout where appropriate.

**Comment by Rainer-Lang** [comment]
Thanks.
